### ISSUE TITLE
Option to always render icons

### ISSUE THREAD

**Issue by Dreadrith** [Dreadrith/HierarchyPlus#12]
Requested by sylvester334.
A settings toggle such as "Always Show" to make stuff render anyway regardless of the space left on the rect.

**Comment by JustBuddy** [comment]
The main feature has been implemented, it was discussed to draw a background for the icons that overdraw the text to improve readability.

**Comment by Dreadrith** [comment]
Implemented with https://github.com/Dreadrith/HierarchyPlus/commit/1eb5350be1cd14fd686b33faae41e47d14542f7e thanks to @JustBuddy 👍
