### ISSUE TITLE
[BUG] [Unity 2022] useCustomGameObjectIcon doesn't function on Unity 2022.

### ISSUE THREAD

**Issue by JustBuddy** [Dreadrith/HierarchyPlus#6]
A previous feature request of mine outside of GitHub asked for these color tags:

![image](https://github.com/Dreadrith/HierarchyPlus/assets/8122264/a654514b-f54d-4cb8-8fdc-3d9215a7beae)

… to be visible in the hierarchy. This works in 2019, but 2022 broke that behavior as it seems.
This option is reflected in the settings as "Use Custom GameObject Icon".

Expected look:
![image](https://github.com/Dreadrith/HierarchyPlus/assets/8122264/b6222728-3467-4b8f-a95a-bd6fcaaf5056)

Same thing in 2022:
![image](https://github.com/Dreadrith/HierarchyPlus/assets/8122264/eec1ccbe-8b1a-462a-ab89-b50f39756d2e)

Tested version: H+ 1.2.0
Fresh projects with nothing but the SDK and H+.

**Comment by JustBuddy** [comment]
I tried to resolve this myself, but had no luck figuring out what is wrong.
H+ uses [EditorGUIUtility](https://docs.unity3d.com/ScriptReference/EditorGUIUtility.html).GetIconForObject, which is present in 2022 just fine.

**Comment by Dreadrith** [comment]
Thank you for trying 👍
Handled with commit https://github.com/Dreadrith/HierarchyPlus/commit/c3c3422216cdc60bb62722abbc013085018a4811
