### ISSUE TITLE
[BUG] Toggling Gameobject also toggles adjacent component.

### ISSUE THREAD

**Issue by JustBuddy** [Dreadrith/HierarchyPlus#7]
**H+ 1.2.0, Unity 2022**

Whenever an GameObject is selected and then toggled, it will also toggle the component next in the list.
This can have unintended impact on animations that toggle just the GameObject.
I couldn't reproduce it consistently, but I believe it is a side-effect of the drag-toggle.
https://splash.buddyworks.wtf/rKT10V7E.gif
![Unity_TtncPUlk3Z](https://github.com/Dreadrith/HierarchyPlus/assets/8122264/1d13d97e-03c4-4e6c-8215-663471535dc6)

In scenarios with more components, only the next component adjacent to the GameObject toggle gets disabled.

**Comment by JustBuddy** [comment]
I could not get this to happen again, will observe in case it was a fluke.
Will close if it never happens again.

**Comment by JustBuddy** [comment]
I was able to make it happen again, but it is highly inconsistent.
It can happen when toggling specific components on a gameobject off if that object has 5 or so components attached to that, like VRCFury Components like here:
![image](https://github.com/Dreadrith/HierarchyPlus/assets/8122264/c028f271-9dcc-4e38-9e12-0db55985fda6)


First assumption is some incompatibility with some other tool.

I'll report back whenever I find a consistent way to reproduce this.

**Comment by Dreadrith** [comment]
It might be some odd Rect manipulation from Unity internally that isn't on 2019 because ADO's scene GUI broke in 2022 in a weird way mostly concerning clicking things. i.e: The Layout and Repaint events had different Rects returned in some cases and what fixed it is to restrict some GUI to the Repaint event.
I'll test it on 2022 at some point and see if I can get it to happen.

**Comment by Dreadrith** [comment]
Should be fixed with https://github.com/Dreadrith/HierarchyPlus/commit/0ecaef5e239a8c53b82a2efa775418e7252681dc
